### ISSUE TITLE
Handling Named-tables with multiple named elements

### ISSUE THREAD

**Issue by mbwhite** [duckdb/substrait#77]
### The substrait integration is experimental. Support is currently only available on request.

- [X] I have permission to ask for support.

### What happens?

- created a Substrait plan from a Calcite relation structure 
- submitted to  duckdb and there is confusion over the name of the tables in question. 
Looking at the code [here..](https://github.com/duckdb/substrait/blob/bafa19b3688ed4c756c1356699a9efeff9ab6de1/src/from_substrait.cpp#L473)

```
try {
	scan = con.Table(sget.named_table().names(0));
} catch (...) {
	scan = con.View(sget.named_table().names(0));
}
```

The list of names is only looking at the first list; in this case the substrait plan had been created via Calcite; based on the schema defined there this had namespaced the  table name "myschema.vehicles"  So duckdb tried to load `myschema` as a table.

Options I see for this:
- this is a duckdb restriction;  this is experimental so a reasonable position, but not ideal. It's not readily easy to update a created Substrait plan to adjust the table names
- I don't believe DuckDB has an namespaces for tables - assuming this then I'd suggest a simple concatination of the names

### To Reproduce

- This needs to have a substrait plan created that includes the multiple namespaces; I'll need to provide a gist or similar as the creation of the plan I have is a Java one, and then consuming in python......

### OS:

Linux

### Substrait-Extension Version:

^0.10.1.dev240

### DuckDB Version:

^0.10.1.dev240

### DuckDB Client:

^0.10.1.dev240

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! As mentioned on the main page, the Substrait extension is currently experimental and we can only process issues from partners and clients at this point in time.
